apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dyc0wh445-nodejs
  janus-idp.io/tekton: dyc0wh445-nodejs
  backstage.io/kubernetes-id: dyc0wh445-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dyc0wh445-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
