apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dyc0wh445-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dyc0wh445-nodejs 
  name: dyc0wh445-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dyc0wh445-nodejs 
